FROM python:3.9
WORKDIR /APP

COPY . ./

RUN pip3 install --upgrade pip

RUN pip3 install uuid
RUN pip3 install typing
RUN pip3 install fastapi
RUN pip3 install jose
RUN pip3 install boto3

RUN apt update -y
RUN apt upgrade -y
RUN apt install curl -y

EXPOSE 80

ENTRYPOINT ['python', 'Booking-Command.py']